<?php
/**
 * app-skeleton-3:/html/index.phtml
 *
 * @creation  2017-07-28
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<div data-i18n="true" data-lang="en">
	<h1>Welcome to uqunie.com</h1>
</div>
<style>
#container {
	_border: 1px solid white;
	margin: auto;
	_max-width: 1000px;
}

#container > article {
	height: 600px;
}

header {
	_border: 1px solid white;
	margin: 0;
}

footer {
	_border: 1px solid white;
	border-radius: 0.25em;
	padding: 0.5em;
	_background-color: #3f3030;
}
</style>